### ISSUE TITLE
Highlighted indexed value does not get selected without manual selection

### ISSUE THREAD

**Issue by LeoJHarris** [npolyak/VSIXRoslynTESTS#1]
Hi there, I like this extension, one thing i noticed is if i start typing and bring up the intellisense and next tap enter it doesn't select the highlighted but the top element that doesn't most closely match what it should. In the GIF I was trying to use the intellisense for the height request but it was closing the tag but didn't seem to pickup that it was a starting tag.

![ezgif com-crop](https://user-images.githubusercontent.com/5468757/38972400-4ff363c8-43f4-11e8-9273-e49e810d1c24.gif)
  
Great extension though

**Comment by npolyak** [comment]
Thanks Leonid! I'll try to take a look over the weekend.
